
server:
  port: 8080
spring:
  application:
    name: zynchub
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  swagger-ui:
    disable-swagger-default-url: true
logging:
  level:
    org.springdoc: TRACE
    org.springframework.web: DEBUG
features:
  file: features.yml
  remote:
    enabled: false
    url: ""
